# Generated by Django 3.2 on 2021-04-14 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre'), (3, 'Otro')], default=3)),
                ('edad', models.PositiveIntegerField()),
                ('gradoEscolar', models.PositiveIntegerField()),
                ('tiempoJuego', models.PositiveIntegerField()),
                ('ramaPreferida', models.IntegerField(choices=[(1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')])),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre'), (3, 'Otro')], default=3)),
                ('edad', models.PositiveIntegerField()),
                ('gradoEscolar', models.PositiveIntegerField()),
                ('token', models.CharField(blank=True, editable=False, max_length=10)),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField()),
                ('tiempo', models.PositiveIntegerField()),
                ('rama', models.IntegerField(choices=[(1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')])),
                ('tiempoTerminacion', models.DateTimeField(null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videojuego.profesor'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
