# Generated by Django 3.2 on 2021-04-27 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre'), (3, 'Otro')], default=3)),
                ('edad', models.PositiveIntegerField()),
                ('gradoEscolar', models.IntegerField(choices=[(1, 'Primaria 1º'), (2, 'Primaria 2º'), (3, 'Primaria 3º'), (4, 'Primaria 4º'), (5, 'Primaria 5º'), (6, 'Primaria 6º'), (7, 'Secundaria 1º'), (8, 'Secundaria 2º'), (9, 'Secundaria 3º')])),
                ('tiempoJuego', models.PositiveIntegerField(blank=True, null=True)),
                ('ramaPreferida', models.IntegerField(blank=True, choices=[(0, 'Indefinido'), (1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')], default=0, null=True)),
                ('profesor', models.CharField(blank=True, max_length=10, null=True)),
                ('personaje', models.IntegerField(choices=[(1, 'Astronauta'), (2, 'Científica')], default=1)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre'), (3, 'Otro')], default=3, null=True)),
                ('edad', models.PositiveIntegerField()),
                ('gradoEscolar', models.PositiveIntegerField(choices=[(1, 'Primaria 1º'), (2, 'Primaria 2º'), (3, 'Primaria 3º'), (4, 'Primaria 4º'), (5, 'Primaria 5º'), (6, 'Primaria 6º'), (7, 'Secundaria 1º'), (8, 'Secundaria 2º'), (9, 'Secundaria 3º')])),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField()),
                ('tiempo', models.FloatField(blank=True, null=True)),
                ('rama', models.IntegerField(choices=[(0, 'Indefinido'), (1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')])),
                ('tiempoTerminacion', models.DateTimeField(null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.jugador')),
            ],
        ),
    ]
