# Generated by Django 3.2 on 2021-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='personaje',
            field=models.IntegerField(choices=[(1, 'Astronauta'), (2, 'Científica')], default=1),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='tiempo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
