# Generated by Django 3.2 on 2021-04-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0002_auto_20210416_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
