# Generated by Django 3.2 on 2021-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0002_auto_20210426_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='ramaPreferida',
            field=models.IntegerField(blank=True, choices=[(0, 'Indefinido'), (1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='rama',
            field=models.IntegerField(choices=[(0, 'Indefinido'), (1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')]),
        ),
    ]
