# Generated by Django 3.2 on 2021-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0004_auto_20210426_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='gradoEscolar',
            field=models.IntegerField(choices=[(1, 'Primaria 1º'), (2, 'Primaria 2º'), (3, 'Primaria 3º'), (4, 'Primaria 4º'), (5, 'Primaria 5º'), (6, 'Primaria 6º'), (7, 'Secundaria 1º'), (8, 'Secundaria 2º'), (9, 'Secundaria 3º')]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='gradoEscolar',
            field=models.PositiveIntegerField(choices=[(1, 'Primaria 1º'), (2, 'Primaria 2º'), (3, 'Primaria 3º'), (4, 'Primaria 4º'), (5, 'Primaria 5º'), (6, 'Primaria 6º'), (7, 'Secundaria 1º'), (8, 'Secundaria 2º'), (9, 'Secundaria 3º')]),
        ),
    ]
