# Generated by Django 3.2 on 2021-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0004_alter_jugador_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='ramaPreferida',
            field=models.IntegerField(blank=True, choices=[(1, 'Ciencia'), (2, 'Tecnología'), (3, 'Ingeniería'), (4, 'Matemáticas')], null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='tiempoJuego',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
