# Generated by Django 3.2 on 2021-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0005_auto_20210416_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='horaFin',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='horaInicio',
        ),
        migrations.AddField(
            model_name='sesion',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='tiempo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
